accounts/urls.py
from django.urls import path
from accounts.views import accounts, admins, managers, customers

app_name = 'accounts'

urlpatterns = [
    path('signup/', accounts.SignUpView.as_view(), name='signup'),
    path('signup/admin/', admins.AdminSignUpView.as_view(), name='admin_signup'),
    path('signup/manager/', managers.ManagerSignUpView.as_view(), name='manager_signup'),
    path('signup/customer/', customers.CustomerSignUpView.as_view(), name='customer_signup'),
]

ecommerce_application/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic.base import TemplateView
from django.contrib.auth.views import LogoutView

from accounts.views.accounts import login_page, guest_register_view
from addresses.views import checkout_address_create_view, checkout_address_reuse_view

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('products/', include('products.urls')),
    path('search/', include('search.urls')),
    path('carts/', include('carts.urls')),
    url(r'^login/$',login_page, name='login'),
    url(r'^register/guest/$', guest_register_view, name='guest_register'),
    url(r'^checkout/address/create/$',checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/address/reuse/$',checkout_address_reuse_view, name='checkout_address_reuse'),
    url(r'^logout/$',LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import home_page, contact_page

app_name = 'home'

urlpatterns = [
    path('', home_page, name='home'),
    path('contact', contact_page, name='contact'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

# Create your views here.


def home_page(request):
    context = {
        "title":"Home Page",
    }
    if request.user.is_authenticated :
        context["premium_content"] = "yeah"
    return render(request, "home/home.html", context)


def contact_page(request):
    context = {
        "title": "Contact Page",
    }
    return render(request, "home/contact.html", context)

home/templates/home/contact.html
{% extends "base.html" %}
{% load static %}

{%  block base_head %}
    <link rel="stylesheet" href="{% static "css/main.css" %}">
{% endblock %}

{% block content %}
<div class="container">
<div class="col-md-auto">
    <b>Contact Here</b>
 </div>
</div>
{% endblock %}

home/templates/home/home.html
{% extends "base.html" %}
{% load static %}

{%  block base_head %}
    <link rel="stylesheet" href="{% static "css/main.css" %}">
{% endblock %}

{% block content %}
<div class="container">
<div class="col-md-auto">
    <diV class="text-center">
        {{ title }}
        <h1>Welcome to the our shop</h1>
        <div class="container">
            <div class="row">
                <div class="col">
                    <img src="{% static 'img/ecommerce.png' %}" class='img-fluid' alt="Image in unable to load"/>
                    {{ premium_content }}
                </div>
            </div>
        </div>
    </div>
 </div>
</div>
{% endblock %}


<!--  {% if user.is_authenticated %}-->
<!--  Hi {{ user.username }}!-->
<!--  <p class="lead"><a href="{% url 'logout' %}" class="btn btn-lg btn-secondary">logout</a></p>-->
<!--{% else %}-->
<!--  <p class="lead">You are not logged in</p>-->
<!--   <p class="lead">-->
<!--  <a href="{% url 'login' %}" class="btn btn-lg btn-secondary">Login</a> |-->
<!--  <a href="{% url 'accounts:signup' %}" class="btn btn-lg btn-secondary">Signup</a>-->
<!--     </p>-->
<!--{% endif %}-->