carts/urls.py
from django.urls import path
from .views import (
    cart_home,
    cart_update,
    checkout_home,
    checkout_done_view,
)

app_name = 'cart'

urlpatterns = [
    path('', cart_home, name='home'),
    path('checkout/', checkout_home, name='checkout'),
    path('update/', cart_update, name='update'),
    path('checkout/success', checkout_done_view, name='success'),
]

ecommerce_application/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic.base import TemplateView
from django.contrib.auth.views import LogoutView

from accounts.views.accounts import login_page, guest_register_view
from addresses.views import checkout_address_create_view, checkout_address_reuse_view

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('products/', include('products.urls')),
    path('search/', include('search.urls')),
    path('carts/', include('carts.urls')),
    url(r'^login/$',login_page, name='login'),
    url(r'^register/guest/$', guest_register_view, name='guest_register'),
    url(r'^checkout/address/create/$',checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/address/reuse/$',checkout_address_reuse_view, name='checkout_address_reuse'),
    url(r'^logout/$',LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import home_page, contact_page

app_name = 'home'

urlpatterns = [
    path('', home_page, name='home'),
    path('contact', contact_page, name='contact'),
]

carts/models.py
from decimal import Decimal
from django.db import models
from django.db.models.signals import m2m_changed,pre_save

from products.models import Product
from accounts.models import User

User = User


class CartManager(models.Manager):

    def new_or_get(self, request):
        cart_id = request.session.get("cart_id", None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = Cart.objects.new(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj

    def new(self, user=None):
        print(user)
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)


class Cart(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE )
    products = models.ManyToManyField(Product, blank=True)
    subtotal = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    total = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)


def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):

    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        products = instance.products.all()
        total = 0
        for x in products:
            total += x.price
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()


m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)


def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal > 0:
        instance.total = Decimal(instance.subtotal) * Decimal(1.08)
    else:
        instance.total = 0.00


pre_save.connect(pre_save_cart_receiver, sender=Cart)

home/models.py
from django.db import models

# Create your models here.

carts/views.py
from django.shortcuts import render, redirect

from .models import Cart
from orders.models import Order
from products.models import Product
from accounts.models import GuestEmail
from billing.models import BillingProfile
from addresses.models import Address
from accounts.forms import LoginForm, GuestForm
from addresses.forms import AddressForm


def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    return render(request, "carts/home.html",{"cart":cart_obj})


def cart_update(request):
    product_id = request.POST.get('product_id')
    if product_id is not None:
        try:
            product_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            print("Show message to user, product is gone?")
            return redirect("cart:home")
        cart_obj, new_obj = Cart.objects.new_or_get(request)
        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj)
        else:
            cart_obj.products.add(product_obj)
        request.session['cart_items'] = cart_obj.products.count()

    return redirect("cart:home")


def checkout_home(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    if cart_created or cart_obj.products.count() == 0:
        return redirect("cart:home")
    login_form = LoginForm()
    guest_form = GuestForm()
    address_form = AddressForm()
    billing_address_id = request.session.get("billing_address_id",None)
    shipping_address_id = request.session.get("shipping_address_id", None)
    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)

    address_qs = None
    if billing_profile is not None:
        if request.user.is_authenticated:
            address_qs = Address.objects.filter(billing_profile=billing_profile)
        order_obj, order_obj_created = Order.objects.new_or_get(billing_profile, cart_obj)
        if shipping_address_id:
            order_obj.shipping_address = Address.objects.get(id = shipping_address_id)
            del request.session["shipping_address_id"]
        if billing_address_id:
            order_obj.billing_address = Address.objects.get(id = billing_address_id)
            del request.session["billing_address_id"]
        if billing_address_id or shipping_address_id:
            order_obj.save()
    if request.method == "POST":
        'check that order is done'
        is_done = order_obj.check_done()
        if is_done:
            order_obj.mark_paid()
            request.session['cart_items'] = 0
            del request.session['cart_id']
            return redirect("cart:success")

    context = {
        "object":order_obj,
        "billing_profile":billing_profile,
        "login_form":login_form,
        "guest_form":guest_form,
        "address_form":address_form,
        "address_qs":address_qs,
    }
    return render(request, "carts/checkout.html", context)


def checkout_done_view(request):
    return render(request, "carts/checkout-done.html",{})

home/views.py
from django.shortcuts import render

# Create your views here.


def home_page(request):
    context = {
        "title":"Home Page",
    }
    if request.user.is_authenticated :
        context["premium_content"] = "yeah"
    return render(request, "home/home.html", context)


def contact_page(request):
    context = {
        "title": "Contact Page",
    }
    return render(request, "home/contact.html", context)

carts/templates/carts/checkout-done.html
 {% extends "base.html" %}

{% block content %}
<div class="col-6 mx-auto py-5 text-center">
    <h1 class="display-1">Thank you for your order!!!  </h1>
</div>
{% endblock %}

carts/templates/carts/checkout.html
{% extends "base.html" %}

{% block content %}


<!--    {{ object.order_id }} &#45;&#45; {{ object.cart }}-->
<div class="container">
    {% if not billing_profile %}
    <div class="row text-center">
        <div class="col-12 col-md-6">
            <p class="lead">Login</p>
            {% include 'accounts/snippets/form.html' with form=login_form next_url=request.build_absolute_uri %}
        </div>
        <div class="col-12 col-md-6">
            Continue as Guest
            {% url 'guest_register' as guest_register_url %}
            {% include 'accounts/snippets/form.html' with form=guest_form next_url=request.build_absolute_uri action_url=guest_register_url %}
        </div>
    </div>

    {% else %}

    {% if not object.shipping_address %}
    <div class="row">
        <div class="col-12">
            <p class="lead">Shipping Address</p>
            <hr/>
        </div>
        <div class="col-6">
            {% url 'checkout_address_create' as checkout_address_create %}
            {% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='shipping' %}
        </div>
        <div class="col-6">
            {% url 'checkout_address_reuse' as checkout_address_reuse %}
            {% include 'addresses/prev_addresses.html' with address_qs=address_qs next_url=request.build_absolute_uri address_type='shipping' action_url=checkout_address_reuse %}
        </div>

    </div>
    {% elif not object.billing_address %}
    <div class="row">
        <div class="col-12">
            <p class="lead">Billing Address</p>
            <hr/>
        </div>
        <div class="col-6">
            {% url 'checkout_address_create' as checkout_address_create %}
            {% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='billing' %}
        </div>
        <div class="col-6">
            {% url 'checkout_address_reuse' as checkout_address_reuse %}
            {% include 'addresses/prev_addresses.html' with address_qs=address_qs next_url=request.build_absolute_uri address_type='billing' action_url=checkout_address_reuse %}
        </div>
    </div>
    {% else %}
    <h1>Finalize Checkout</h1>
    <p>Cart Items: {% for product in object.cart.products.all %}
        {{ product }}
        {% if not forloop.last %}, {% endif %}
        {% endfor %}
    </p>
    <p>Shipping Address: {{ object.shipping_address.get_address }}</p>
    <p>Billing Address: {{ object.billing_address.get_address }}</p>
    <p>Cart Total: {{ object.cart.total }}</p>
    <p>Shipping Total: {{ object.shipping_total }}</p>
    <p>Order Total: {{ object.total }}</p>

    <form class="form" method="POST" action="">
        {% csrf_token %}
        <button type="submit" class="btn btn-success">Checkout</button>
    </form>
    {% endif %}

    {% endif %}
</div>
{% endblock %}

carts/templates/carts/home.html
{% extends "base.html" %}

{% block content %}
    <h1>Cart</h1>

    {% if cart.products.exists %}

        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Product Name</th>
                <th scope="col">Product price</th>
            </tr>
            </thead>
            <tbody>
            {% for product in cart.products.all %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td><a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                        {% include 'products/snippets/update-cart.html' with product=product cart=cart in_cart=True %}
                    </td>
                    <td>{{ product.price }}</td>
                </tr>
            {% endfor %}
            <tr>
                <td colspan="2"></td>
                <td><b>Subtotal</b>{{ cart.subtotal }}</td>
            </tr>
            <tr>
                <td colspan="2"></td>
                <td><b>Total</b>{{ cart.total }}</td>
            </tr>
            <tr>
                <td colspan="2"></td>
                <td><a class="btn btn-lg btn-success" href="{% url 'cart:checkout' %}">Checkout</a></td>
            </tr>
            </tbody>
        </table>
    {% else %}
        <p class="lead">Cart is empty</p>
    {% endif %}
{% endblock %}