accounts/urls.py
from django.urls import path
from accounts.views import accounts, admins, managers, customers

app_name = 'accounts'

urlpatterns = [
    path('signup/', accounts.SignUpView.as_view(), name='signup'),
    path('signup/admin/', admins.AdminSignUpView.as_view(), name='admin_signup'),
    path('signup/manager/', managers.ManagerSignUpView.as_view(), name='manager_signup'),
    path('signup/customer/', customers.CustomerSignUpView.as_view(), name='customer_signup'),
]

carts/urls.py
from django.urls import path
from .views import (
    cart_home,
    cart_update,
    checkout_home,
    checkout_done_view,
)

app_name = 'cart'

urlpatterns = [
    path('', cart_home, name='home'),
    path('checkout/', checkout_home, name='checkout'),
    path('update/', cart_update, name='update'),
    path('checkout/success', checkout_done_view, name='success'),
]

ecommerce_application/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic.base import TemplateView
from django.contrib.auth.views import LogoutView

from accounts.views.accounts import login_page, guest_register_view
from addresses.views import checkout_address_create_view, checkout_address_reuse_view

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('products/', include('products.urls')),
    path('search/', include('search.urls')),
    path('carts/', include('carts.urls')),
    url(r'^login/$',login_page, name='login'),
    url(r'^register/guest/$', guest_register_view, name='guest_register'),
    url(r'^checkout/address/create/$',checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/address/reuse/$',checkout_address_reuse_view, name='checkout_address_reuse'),
    url(r'^logout/$',LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import home_page, contact_page

app_name = 'home'

urlpatterns = [
    path('', home_page, name='home'),
    path('contact', contact_page, name='contact'),
]

products/urls.py
from django.urls import path
from .views import ProductListView, ProductDetailSlugView

app_name = 'products'

urlpatterns = [
    path('list', ProductListView.as_view(), name='list'),
    # path('details/<int:pk>/', ProductDetailView.as_view(), name='details'),
    path('details/<slug:slug>/',ProductDetailSlugView.as_view(),name='details')

]

templates/base/css.html
{% load static %}
<!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<!--Font awesome CDN-->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

templates/base/js.html
{% load static %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

templates/base/navbar.html
{% load static %}

{% url 'home:home' as home_url %}
{% url 'home:contact' as contact_url %}
{% url 'products:list' as product_list_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'accounts:customer_signup' as signup_url %}
{% url 'cart:home' as cart_url %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
    <div class="container">
        <a class="navbar-brand" href="{{ home_url }}">
            <img src="{% static 'img/logo.png' %}" width="30" height="30"
                 class="d-inline-block align-top" alt="Bo">
        </a>
        <a class="navbar-brand" href="{{ home_url }}">
            {% if brand_name %}
                {{ brand_name }}
            {% else %}
                CFE eCommerce
            {% endif %}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
                aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item {% if request.path == home_url %}active{% endif %}">
                    <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
                    <a class="nav-link" href="{{ contact_url }}">Contact</a>
                </li>
                <li class="nav-item {% if request.path == product_list_url %}active{% endif %}">
                    <a class="nav-link" href="{{ product_list_url }}">Product</a>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item {% if request.path == logout_url %}active{% endif %}">
                        <a class="nav-link" href="{{ logout_url }}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item {% if request.path == signup_url %}active{% endif %}">
                        <a class="nav-link" href="{{ signup_url }}">Register</a>
                    </li>
                    <li class="nav-item {% if request.path == login_url %}active{% endif %}">
                        <a class="nav-link" href="{{ login_url }}">Login</a>
                    </li>
                {% endif %}

                 <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
                    <a class="nav-link" href="{{ cart_url }}">{{ request.session.cart_items }}&nbsp;<i class="fas fa-shopping-cart"></i> </a>
                </li>

            </ul>
            {% include 'search/snippets/search-form.html' %}
        </div>
    </div>
</nav>